### PR TITLE
Remove lapacke library from cacao plugin

### PR DESCRIPTION
**Pull request by drbitboy**
The mkl-sdl (single dynamic library, libmkl_rt.*) has all of the lapack and cblas entry points, so lapacke is not required when using mkl-sdl and can be removed from CMakeLists.txt under plugins/cacao-src/computeCalib

This has been made necessary by [this commit](https://github.com/milk-org/milk/commit/07f1cd4e2fd406269342ac5d88dc0bc4ccd34336) cf. [here](https://github.com/milk-org/milk/blame/dev/CMakeLists.txt#L43).

### CODE REVIEW

**Review by DasVinch — APPROVED** [review]

**Comment by drbitboy** [comment]
This should be done in cacao, but I am not a member of cacao-org.

**Comment by jaredmales** [comment]
@oguyon @DasVinch do we actually need to link against lapacke?  Or is lapacke installed just to get lapack.h for openblas? (which has lapack in it, but doesn't bring the header on ubuntu for "reasons")

**Comment by drbitboy** [comment]
It might be worth waiting on this and making the change directly to the CACAO repo.

**Comment by drbitboy** [comment]
The latest commit, https://github.com/milk-org/milk/pull/12/commits/533c0168be611a7b57b7c028914f0661c07682d2, will provide flexibility in future to use a CACAO branch other than dev from https://github.com/cacao-org/cacao.git.

**Pull request merged**
